/* tslint:disable */
/* eslint-disable */
/**
 * Healix Clinic Management API
 * REST API for clinic management system with EHR support for Maharashtra small to mid-sized clinics.  ## Features - Patient registration and management - Emergency contact management - Insurance details tracking - Medical history records 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@healix.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { InsuranceScheme } from '../models';
/**
 * InsuranceSchemesApi - axios parameter creator
 */
export const InsuranceSchemesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Retrieve all active insurance schemes ordered by display order
         * @summary Get all active insurance schemes
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllActiveSchemes: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/insurance-schemes`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get GOVERNMENT or PRIVATE insurance schemes
         * @summary Get schemes by type
         * @param {GetSchemesByTypeSchemeTypeEnum} schemeType Scheme type (GOVERNMENT or PRIVATE)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSchemesByType: async (schemeType: GetSchemesByTypeSchemeTypeEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'schemeType' is not null or undefined
            assertParamExists('getSchemesByType', 'schemeType', schemeType)
            const localVarPath = `/api/insurance-schemes/type/{schemeType}`
                .replace(`{${"schemeType"}}`, encodeURIComponent(String(schemeType)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * InsuranceSchemesApi - functional programming interface
 */
export const InsuranceSchemesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = InsuranceSchemesApiAxiosParamCreator(configuration)
    return {
        /**
         * Retrieve all active insurance schemes ordered by display order
         * @summary Get all active insurance schemes
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllActiveSchemes(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<InsuranceScheme>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllActiveSchemes(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InsuranceSchemesApi.getAllActiveSchemes']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get GOVERNMENT or PRIVATE insurance schemes
         * @summary Get schemes by type
         * @param {GetSchemesByTypeSchemeTypeEnum} schemeType Scheme type (GOVERNMENT or PRIVATE)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSchemesByType(schemeType: GetSchemesByTypeSchemeTypeEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<InsuranceScheme>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSchemesByType(schemeType, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InsuranceSchemesApi.getSchemesByType']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * InsuranceSchemesApi - factory interface
 */
export const InsuranceSchemesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = InsuranceSchemesApiFp(configuration)
    return {
        /**
         * Retrieve all active insurance schemes ordered by display order
         * @summary Get all active insurance schemes
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllActiveSchemes(options?: RawAxiosRequestConfig): AxiosPromise<Array<InsuranceScheme>> {
            return localVarFp.getAllActiveSchemes(options).then((request) => request(axios, basePath));
        },
        /**
         * Get GOVERNMENT or PRIVATE insurance schemes
         * @summary Get schemes by type
         * @param {GetSchemesByTypeSchemeTypeEnum} schemeType Scheme type (GOVERNMENT or PRIVATE)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSchemesByType(schemeType: GetSchemesByTypeSchemeTypeEnum, options?: RawAxiosRequestConfig): AxiosPromise<Array<InsuranceScheme>> {
            return localVarFp.getSchemesByType(schemeType, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * InsuranceSchemesApi - object-oriented interface
 */
export class InsuranceSchemesApi extends BaseAPI {
    /**
     * Retrieve all active insurance schemes ordered by display order
     * @summary Get all active insurance schemes
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAllActiveSchemes(options?: RawAxiosRequestConfig) {
        return InsuranceSchemesApiFp(this.configuration).getAllActiveSchemes(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get GOVERNMENT or PRIVATE insurance schemes
     * @summary Get schemes by type
     * @param {GetSchemesByTypeSchemeTypeEnum} schemeType Scheme type (GOVERNMENT or PRIVATE)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getSchemesByType(schemeType: GetSchemesByTypeSchemeTypeEnum, options?: RawAxiosRequestConfig) {
        return InsuranceSchemesApiFp(this.configuration).getSchemesByType(schemeType, options).then((request) => request(this.axios, this.basePath));
    }
}

export const GetSchemesByTypeSchemeTypeEnum = {
    Government: 'GOVERNMENT',
    Private: 'PRIVATE'
} as const;
export type GetSchemesByTypeSchemeTypeEnum = typeof GetSchemesByTypeSchemeTypeEnum[keyof typeof GetSchemesByTypeSchemeTypeEnum];
